version: '3.9'

services:
  database:
    # Registers hostname in localdev network this must be unique
    hostname: ${POSTGRES_HOST}
    image: postgres:latest
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-lms-database-1}
      - POSTGRES_USER=${POSTGRES_USER:-lms}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-lms}
      - POSTGRES_DB=${POSTGRES_DB:-lms}
      - TZ=${TIME_ZONE:-Europe/Amsterdam}
    restart: always
    ports:
      - ${POSTGRES_PORT:-5433}:5432
    networks:
      - localdev
    volumes:
      - lms-database:/var/lib/postgresql/data
    env_file:
      - ./.env

  api:
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    depends_on:
      - database
    ports:
      - "${DOTNET_PORT:-5005}:5005"
    networks:
      - localdev
    environment:
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=${TIME_ZONE}
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_HOST}; Database=${POSTGRES_DB}; Username=${POSTGRES_USER}; Password=${POSTGRES_PASSWORD};
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
    volumes:
      - ./services/api:/api
    tty: true
    env_file:
      - ./.env
    restart: always

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - api
    restart: always
    volumes:
      - ./services/web:/web
    tty: true
    ports:
      - ${NODE_PORT:-81}:5173
    env_file:
      - ./.env
    networks:
      - localdev
    
networks:
  localdev:

volumes:
  lms-database:
